In [47]:
import pandas as pd
import numpy as np

In [49]:
golf = pd.read_csv("golf.csv")

In [51]:
golf

     Outlook Temperature Humidity  Windy Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [53]:
from sklearn.preprocessing import LabelEncoder

In [55]:
le1 = LabelEncoder()
golf['Outlook'] = le1.fit_transform(golf['Outlook'])
le2 = LabelEncoder()
golf['Temperature'] = le2.fit_transform(golf['Temperature'])
le3 = LabelEncoder()
golf['Humidity'] = le3.fit_transform(golf['Humidity'])
le4 = LabelEncoder()
golf['Windy'] = le4.fit_transform(golf['Windy'])
le5 = LabelEncoder()
golf['Play'] = le5.fit_transform(golf['Play'])

In [57]:
golf.head()

   Outlook  Temperature  Humidity  Windy  Play
0        2            1         0      0     0
1        2            1         0      1     0
2        0            1         0      0     1
3        1            2         0      0     1
4        1            0         1      0     1

In [59]:
from sklearn.naive_bayes import CategoricalNB

In [61]:
model = CategoricalNB()

In [63]:
model.fit(golf.iloc[:, :-1], golf.iloc[:, -1])

CategoricalNB()

In [65]:
X_test = ["sunny", "hot", "normal", False]

In [76]:
# le1.transform(['sunny'])
# le2.transform(['hot'])
# le3.transform(['normal'])
# le4.transform([False])

In [78]:
X_test = np.array([[2,1,1,0]])

In [80]:
model.predict(X_test)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(

array([1])

In [82]:
model.predict_proba(X_test)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(

array([[0.33508723, 0.66491277]])